# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.0.5
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-08-28T12:26:08Z"
  labels:
    app: devine
  name: devine
spec:
  containers:
  - command:
    - postgres
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: PG_MAJOR
      value: "13"
    - name: PG_VERSION
      value: 13beta3
    - name: PG_SHA256
      value: 863e33ee9d1099e2a0f1cab6dbd015789b2c2af75cfbad814a3acdf7c8eeaf9d
    - name: container
      value: podman
    - name: LANG
      value: en_US.utf8
    - name: PGDATA
      value: /var/lib/postgresql/data
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: HOSTNAME
      value: devine
    image: docker.io/library/postgres:13-alpine
    name: postgres
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  - command:
    - /bin/ash
    - -l
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: GOPRIVATE
      value: github.com/anhuret
    - name: GONOPROXY
      value: github.com/anhuret
    - name: CGO_ENABLED
      value: "0"
    - name: container
      value: podman
    - name: HOSTNAME
      value: devine
    image: localhost/devine:latest
    name: code
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - CAP_DAC_READ_SEARCH
        - CAP_LINUX_IMMUTABLE
        - CAP_NET_BROADCAST
        - CAP_NET_ADMIN
        - CAP_IPC_LOCK
        - CAP_IPC_OWNER
        - CAP_SYS_MODULE
        - CAP_SYS_RAWIO
        - CAP_SYS_PTRACE
        - CAP_SYS_PACCT
        - CAP_SYS_ADMIN
        - CAP_SYS_BOOT
        - CAP_SYS_NICE
        - CAP_SYS_RESOURCE
        - CAP_SYS_TIME
        - CAP_SYS_TTY_CONFIG
        - CAP_LEASE
        - CAP_AUDIT_CONTROL
        - CAP_MAC_OVERRIDE
        - CAP_MAC_ADMIN
        - CAP_SYSLOG
        - CAP_WAKE_ALARM
        - CAP_BLOCK_SUSPEND
        - CAP_AUDIT_READ
      privileged: true
      readOnlyRootFilesystem: false
      runAsGroup: 1000
      runAsUser: 1000
      seLinuxOptions: {}
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /home/ruslan/code
      name: home-ruslan-code
    workingDir: /home/ruslan
  volumes:
  - hostPath:
      path: /home/ruslan/code
      type: Directory
    name: home-ruslan-code
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}
